# Generated by Django 4.0.5 on 2022-06-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        ('workouts', '0002_remove_workout_exercises_workout_exercises_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workouts', models.ManyToManyField(related_name='favorites', to='workouts.workout')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercises', models.ManyToManyField(related_name='favorites', to='exercises.exercise')),
            ],
        ),
    ]
