# Generated by Django 4.0.5 on 2022-06-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteexercise',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='favoriteworkout',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
