# Generated by Django 4.0.5 on 2022-06-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('description', models.TextField(default=None, max_length=3000)),
                ('how_to_do', models.TextField(default=None, max_length=3000)),
                ('sets', models.PositiveBigIntegerField(default=None)),
                ('image', models.CharField(default=None, max_length=3000)),
                ('video', models.CharField(max_length=300)),
                ('expert_opinions', models.TextField(default=None, max_length=3000)),
                ('groups', models.ManyToManyField(related_name='exercises', to='groups.group')),
            ],
        ),
    ]
