# Generated by Django 4.0.5 on 2022-06-10 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('exercises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='exercises.exercise')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='groups.group')),
            ],
        ),
    ]
