# Generated by Django 4.0.5 on 2022-07-14 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0002_remove_workout_exercises_workout_exercises_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='groups',
        ),
        migrations.AddField(
            model_name='workout',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
